name: deploy-infra

on:
  push:
    paths:
      - 'infra/**'
  workflow_dispatch: {}

env:
  RESOURCE_GROUP_DEV: aguadamillas_students_1
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: sofia

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter main
      run: az bicep build --file ./infra/main.bicep

    - name: Run Bicep linter key-vault
      run: az bicep build --file ./infra/key-vault.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:
      - uses: actions/checkout@main
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Key Vault
        id: deploy-kv
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/key-vault.bicep
          parameters: ./infra/parameters/key-vault.json
          deploymentName: '${{ env.USER_ALIAS }}-kv'
          failOnStdErr: false

      - name: Deploy Main Bicep file
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/main.bicep
          parameters: ./infra/parameters/parameters.json
          deploymentName: ${{ env.USER_ALIAS }}
          failOnStdErr: false