name: Deploy App
on: [push, workflow_dispatch]

env:
  IMAGE_NAME: flask-demo
  REGISTRY_URL: sofiaex3registry.azurecr.io
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Login to Docker Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set image version
        id: image-version
        run: echo "::set-output name=version::$(date +'%Y.%m.%d.%H.%M')"

      - name: "Build and push image"
        run: |
          docker build . -t ${{ env.REGISTRY_URL}}/${{ env.IMAGE_NAME }}:${{ steps.image-version.outputs.version }}
          docker build . -t ${{ env.REGISTRY_URL}}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-latest
          docker push ${{ env.REGISTRY_URL}}/${{ env.IMAGE_NAME }}:${{ steps.image-version.outputs.version }}
          docker push ${{ env.REGISTRY_URL}}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-latest

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "sofiaEx3Webapp"
          images: "${{ env.REGISTRY_URL }}/${{env.IMAGE_NAME}}:latest"
