name: deploy-infra

on:
  push:
    paths:
      - '.github/**' 
  workflow_dispatch:

env:
  RESOURCE_GROUP_DEV: aguadamillas_students_1
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: smoreno
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Print current directory
      - name: Print current directory
        run: |
          pwd
          ls -R

      # Lint Bicep code for key-vault.bicep
      - name: Run Bicep Linter for key-vault.bicep
        run: |
          pwd
          cd .github/infra  # Navigate to the correct path
          ls -R
          az bicep build --file key-vault.bicep

      # Lint Bicep code for main.bicep
      - name: Run Bicep Linter for main.bicep
        run: |
          pwd
          cd .github/infra  # Navigate to the correct path
          ls -R
          az bicep build --file main.bicep

  deploy:
    #if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy key vault so that it can be referenced by the main.bicep file
      - name: deploy-key-vault
        uses: azure/arm-deploy@v1.0.9
        with:
          scope : 'subscription'
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: .github/infra/key-vault.bicep  
          parameters: .github/infra/parameters/key-vault.json  # Adjusted the path
          deploymentName: '${{env.USER_ALIAS}}-kv'
          failOnStdErr: false

      # Deploy Bicep File
      - name: deploy-main
        uses: azure/arm-deploy@v1.0.9
        with:
          scope: /subscriptions/${{ env.SUBSCRIPTION_ID_DEV }}/resourceGroups/${{ env.RESOURCE_GROUP_DEV }}
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: .github/infra/main.bicep  # Adjusted the path
          parameters: .github/infra/parameters/main.json  # Adjusted the path
          deploymentName: ${{env.USER_ALIAS}}
          failOnStdErr: false
